name: Brew CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Homebrew update
        run: brew update

      - name: Brew style/audit (non-blocking)
        run: |
          brew style Formula/sup.rb || true
          brew audit --new --strict sup || true

      - name: Install SUP from tap
        run: |
          brew untap "${{ github.repository }}" || true
          brew tap "${{ github.repository }}"
          brew install --formula "${{ github.repository }}/sup"
          brew list --versions sup

      - name: Smoke test
        run: |
          cat > hello.sup <<'EOF'
          sup
            print "Hello, SUP!"
          bye
          EOF
          sup hello.sup | grep "Hello, SUP!"


